### ISSUE TITLE
can I add a zip with an easier to understand set of things to do for people who aren't coders

### ISSUE THREAD

**Issue by CoffeeIsLife87** [lucienmaloney/BeatSaber.jl#3]
[maptooleasy.zip](https://github.com/lucienmaloney/BeatSaber.jl/files/4330335/maptooleasy.zip)

could you make that a release

**Comment by lucienmaloney** [comment]
I'm all for making the setup process more understandable for beginners, but I think a better approach over a zip file would just be to improve the instructions in the Readme. Maybe go into more detail and provide platform-specific steps. You're free to make edits there if you like.

I'm also working on a JavaScript port so that the whole util can run in the browser, no setup required. It'll be slower than what we have now, but it should make the interface usable by anyone.

**Comment by CoffeeIsLife87** [comment]
that sounds good

**Comment by CoffeeIsLife87** [comment]
I dont think you have it open for editing

**Comment by lucienmaloney** [comment]
You should be able to fork the repo, make changes to the Readme, and submit a pull request. If not, let me know and I'll look into it.
