### ISSUE TITLE
Playability

### ISSUE THREAD

**Issue by davidvandertuijn** [lucienmaloney/BeatSaber.jl#5]
First of all i like the idea of generating BeasSaber maps automaticly, the audio download from YouTube is also very usefull, since MP3 has become oldscool and hard to find. I am a software developer but not a music expert, one of my favorites songs with a easy beat is: https://www.youtube.com/watch?v=xpGXNnYo0YY . I use this song with this software and i encounter the following issues:

- The only difficulty is expert+, a hard/expert difficulty would be more playable.
- The sequence of the blocks is sometimes to quick behind each other, maybe because i am not an expert+ :)
- There is also a lot of diagonal blocks, while i preffer more up, and down slashes. or horizontal.
- Some blocks cloud rather be left away, and focus on the main beat.
- A successfull map, also has a fun element in playing, if you know what i mean.

**Comment by lucienmaloney** [comment]
The ability to map all difficulties is definitely a feature I intend to add in the future. Hopefully the not-so-distant one, but there are still a couple of obstacles I'm trying to overcome.

The biggest problem for generating easier maps is the beat detection. I'm also no music expert, and I'm not a DSP expert either, so the current function that turns audio data into timestamps for note placements is a bit... unrefined. Expert+ maps allow you to cheese it a bit, because when laying out a lot of notes, the chances that enough of them fall on the right beats to seem mostly natural are pretty good. It doesn't quite work for all songs (yet?), but for most of them the timing is okay. Counterintuitively, simpler maps are harder to generate well, because the less notes on the field the more on-point they have to be or things don't feel right.

So I am trying to get all difficulty levels working, but I have no idea how long it'll take (or if it will require outside help). The good news is that once the beat timestamps are sorted out, the suggestions you made for simpler flow will be relatively easy to make. Just a few variables to tweak there, I think. In the meantime, feel free to leave any other feedback or ideas you have, or monkey around with the code.

**Comment by lucienmaloney** [comment]
@davidvandertuijn I've just pushed the commit to add in different difficulty mappings. Now running the utility should produce all 5 standard map levels. If you feel like testing it out now, please let me know what you think afterward, so I can make adjustments as necessary
